name: godsufficient
description: "Free Christian Resources"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.19.1
  flutter_bloc: ^9.1.1
  firebase_core: ^3.15.1
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  validateit:
    git:
      url: https://github.com/JadyMcIntyre/validate.it.git
      path: validateit
  firebase_auth: ^5.6.2
  equatable: ^2.0.7
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true