// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbcU5hHlTn0aYm8HDlxA_HXk0rJ8paEKs',
    appId: '1:68940100303:web:4ae60f4107136360fa7dba',
    messagingSenderId: '68940100303',
    projectId: 'godsufficient-5c827',
    authDomain: 'godsufficient-5c827.firebaseapp.com',
    storageBucket: 'godsufficient-5c827.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjAnYVj4jNVe1lZBigjOFOHz9Ck2ifEAc',
    appId: '1:68940100303:android:aa6644fd1f550159fa7dba',
    messagingSenderId: '68940100303',
    projectId: 'godsufficient-5c827',
    storageBucket: 'godsufficient-5c827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWq0J9XGDfAoUsz_oFBWJKbKfM9IkMkTU',
    appId: '1:68940100303:ios:9a7af8ad9a231498fa7dba',
    messagingSenderId: '68940100303',
    projectId: 'godsufficient-5c827',
    storageBucket: 'godsufficient-5c827.firebasestorage.app',
    iosBundleId: 'com.godsufficient.godsufficient',
  );
}
